#
# Copyright (C) 2015 Imagination Technologies
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y += cmd_elfload.o
obj-y += cmd_sram.o
obj-y += ddr.o
obj-y += lcd.o
obj-y += lowlevel_init.o
obj-y += sead3.o
