/*
 * Copyright (C) 2016 Imagination Technologies
 *
 * SPDX-License-Identifier:	GPL-2.0
 */

#ifndef __BOARD_BOSTON_REGS_H__
#define __BOARD_BOSTON_REGS_H__

#include <asm/addrspace.h>

#define BOSTON_PLAT_BASE		CKSEG1ADDR(0x17ffd000)
#define BOSTON_LCD_BASE			CKSEG1ADDR(0x17fff000)

/*
 * Platform Register Definitions
 */
#define BOSTON_PLAT_CORE_CL		(BOSTON_PLAT_BASE + 0x04)

#define BOSTON_PLAT_SOFT_RST		(BOSTON_PLAT_BASE + 0x10)
# define BOSTON_PLAT_SOFT_RST_SYSTEM	(0x1 << 4)

#define BOSTON_PLAT_DDR3STAT		(BOSTON_PLAT_BASE + 0x14)
# define BOSTON_PLAT_DDR3STAT_CALIB	(1 << 2)

#define BOSTON_PLAT_SPARE0				(BOSTON_PLAT_BASE + 0x20)
# define BOSTON_PLAT_SPARE0_IC_AWCACHE			(0xf << 20)
# define BOSTON_PLAT_SPARE0_IC_AWCACHE_COH_NOALLOC	(0x4 << 20)
# define BOSTON_PLAT_SPARE0_IC_AWCACHE_COH_ALLOC	(0x8 << 20)
# define BOSTON_PLAT_SPARE0_IC_ARCACHE			(0xf << 24)
# define BOSTON_PLAT_SPARE0_IC_ARCACHE_COH_ALLOC	(0x4 << 24)
# define BOSTON_PLAT_SPARE0_IC_ARCACHE_COH_NOALLOC	(0x8 << 24)

#define BOSTON_PLAT_BUILDCFG0		(BOSTON_PLAT_BASE + 0x34)
# define BOSTON_PLAT_BUILDCFG0_IOCU	(0x1 << 0)
# define BOSTON_PLAT_BUILDCFG0_CFG_LTR	(0xf << 4)
# define BOSTON_PLAT_BUILDCFG0_CFG_NUM	(0xff << 8)
# define BOSTON_PLAT_BUILDCFG0_DP	(0x1 << 24)
# define BOSTON_PLAT_BUILDCFG0_DP_MULT	(0xf << 28)

#define BOSTON_PLAT_DDRCONF0		(BOSTON_PLAT_BASE + 0x38)
# define BOSTON_PLAT_DDRCONF0_SIZE	(0xf << 0)

#define BOSTON_PLAT_NOCPCIE0ADDR	(BOSTON_PLAT_BASE + 0x3c)
#define BOSTON_PLAT_NOCPCIE1ADDR	(BOSTON_PLAT_BASE + 0x40)
#define BOSTON_PLAT_NOCPCIE2ADDR	(BOSTON_PLAT_BASE + 0x44)

#endif /* __BOARD_BOSTON_REGS_H__ */
