#
# Copyright (C) 2016 Imagination Technologies
#
# SPDX-License-Identifier:	GPL-2.0
#

obj-y += bdinfo.o
obj-y += checkboard.o
obj-y += ddr.o
obj-y += display.o
obj-y += dt.o
obj-y += early_init_r.o
obj-y += iocu.o
obj-y += lowlevel_init.o
obj-y += misc_init_r.o
obj-y += mmc.o
obj-y += reset.o
